### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by steel101** [tamimcpp/webView#1]
I

**Comment by steel101** [comment]
I have been trying I can't get task assemble to work to make a apk

**Comment by thisistamim** [comment]
It looks like you've added a workflow to generate an APK and upload it as an artifact to GitHub.
Here are some common troubleshooting steps you can take:
- Check Workflow Execution Logs
- Verify Environment Setup
- Verify Paths and File Names
- Check Permissions
- Test Locally
- Review Error Messages
- Check GitHub Actions Status

I hope you'll have comprehensive automation for building and releasing your Android app on GitHub. `Happy Building!!`

**Comment by steel101** [comment]
It won't allow gradle assemble to run it errors out saying no task. I have used the same gradle file I always use to build apps but your app will not build on GitHub but works just fine on my local computer. Could you try to see if you can get a griddle to build the app on GitHub workflows and help me because at this point I'm stuck. I have went ahead and made a new app that uses system webview as I could get it to build but not webview by it self
